SELECT (COUNT(DISTINCT ?entity) AS ?totalEntityCount)
WHERE {
  {
    ?entity ?predicate ?object .
    FILTER(REGEX(STR(?entity), "^http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#"))
  }
  UNION
  {
    ?subject ?predicate ?entity .
    FILTER(REGEX(STR(?entity), "^http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#"))
  }
}