SELECT DISTINCT ?entity
WHERE {
  {
    ?entity ?predicate ?object .
    FILTER(REGEX(STR(?entity), "^http://www.wikidata.org/entity/"))
  }
  UNION
  {
    ?subject ?predicate ?entity .
    FILTER(REGEX(STR(?entity), "^http://www.wikidata.org/entity/"))
  }
}
ORDER BY ?entity